### ISSUE TITLE
Readability issues

### ISSUE THREAD

**Issue by benfishbus** [feediron/ttrss_plugin-feediron#184]
Are the steps in the readme for installing readability current? I just followed them, only to be told:
`Package andreskrey/readability.php is abandoned, you should avoid using it. Use fivefilters/readability.php instead.`

FWIW, I needed to install a bunch more php8 modules than indicated by the readme:
docker compose exec app apk add php8-phar _**php8-openssl php8-iconv php8-curl php8-dom php8-xml php8-mbstring**_

* Operating System: ttrss-docker-compose
* TTRSS version/git version: v22.09-42bc162
* PHP version: 8.0.22
* Feediron Configuration: available if needed

**Comment by dugite-code** [comment]
I haven't updated the readability package on my install for a while, It's not been broken so I haven't fixed it. I'm using the docker container and I note it's now using `php81-*` for all these packages (excluding the phar package) https://git.tt-rss.org/fox/ttrss-docker-compose.git/tree/app/Dockerfile so that's probably the issue. `sudo docker-compose exec app apk add php81-phar`

**Comment by dugite-code** [comment]
Ok I found some time to look into things. Looks like I was a bit behind on updates myself

Looks like fivefilters have not done a proper release yet and the v2.1 release has the andreskrey namespace so it won't work, that said in php8.1 I'm seeing a few deprecation notices so still using andreskrey isn't ideal. Fox has forked the Readability.PHP and is currently maintaining it for use in `af_readability` So I have switched to this for now. I've also updated the instructions for PHP-8.1 If you're using the latest container you shouldn't have `PHP version: 8.0.22`
